# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19382c8d0721b664c81928cd163187716780215f08be1f8b5e1abf8dfff7a26aca5007c497b614804ace70ff58c42c28e83be7efd847868b1a81a27f6a82ecdb

test:
  secret_key_base: d2bcda99dfbbba2b3937bfc810d05d38cd3bbbc6e86858d2c12de7b8be751aea4ea3dfcad1c53e164be4e84a4572b402e17857428b50cc3468d408006e6436bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
